### PR TITLE
add ruby-choccy layout

### PR DESCRIPTION
**Pull request by ember-ana**
[ruby-choccy](https://ravy.dev/ruby-choccy) is a fork of [pashutk/chocofi](https://github.com/pashutk/chocofi).

chocofi uses the Corne layout and firmware, then just ignores the extra columns (0 and 12).
one of the changes we made is to properly remove those [in firmware](https://ravy.dev/ruby-choccy/firmware), which means the keymaps are different, so using Corne in the layout editor doesn't work.

chocofi also has a much more aggressive column stagger than Corne. i adjusted that in the config as well :)

thanks in advance!!

### CODE REVIEW

**Comment by nickcoutsos** [comment]
Hey thanks!

**Comment by ember-ana** [comment]
i was wondering whether/when this layout is going to be available in the web editor 🥺

**Comment by nickcoutsos** [comment]
Hey, sorry, I've been a bit under the weather and wasn't able to push a new release. It should have the new layout available now.

**Comment by ember-ana** [comment]
no worries at all, i was just genuinely confused :)

**Pull request merged**
